// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDryBFhyVIwHtx7P5Jzhiq88Dq57rl4ftQ',
    appId: '1:437647225459:web:c4dab3bbd0513f3aad3006',
    messagingSenderId: '437647225459',
    projectId: 'flutter-app-79e87',
    authDomain: 'flutter-app-79e87.firebaseapp.com',
    databaseURL: 'https://flutter-app-79e87-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-79e87.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDL8aglzcek8BAsSnFWWk197v9WlvRvgM',
    appId: '1:437647225459:android:af0a34292be4b470ad3006',
    messagingSenderId: '437647225459',
    projectId: 'flutter-app-79e87',
    databaseURL: 'https://flutter-app-79e87-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-79e87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW6McjMmNXa8BTNQ1mR2SvhEqWCM4DTuM',
    appId: '1:437647225459:ios:cf682ddde45bab05ad3006',
    messagingSenderId: '437647225459',
    projectId: 'flutter-app-79e87',
    databaseURL: 'https://flutter-app-79e87-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-79e87.appspot.com',
    iosClientId: '437647225459-c7leplf0dd9tru2isc508eeu9lrk42cu.apps.googleusercontent.com',
    iosBundleId: 'com.example.maxel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW6McjMmNXa8BTNQ1mR2SvhEqWCM4DTuM',
    appId: '1:437647225459:ios:cf682ddde45bab05ad3006',
    messagingSenderId: '437647225459',
    projectId: 'flutter-app-79e87',
    databaseURL: 'https://flutter-app-79e87-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-79e87.appspot.com',
    iosClientId: '437647225459-c7leplf0dd9tru2isc508eeu9lrk42cu.apps.googleusercontent.com',
    iosBundleId: 'com.example.maxel',
  );
}
